default: &default
  adapter: sqlite3
  timeout: 5000

development:
  <<: *default
  database: db/project-app-dev.sqlite3

production:
  <<: *default
  database: db/project-app-prod.db

test:
  <<: *default
  database: db/project-app-test.sqlite3